
robot1:
  topics:
    - /robot1/wp
    - /robot1/pose
  pose:
    - 0.0
    - 0.0
    - 0.0
robot2:
  topics:
    - /robot2/wp
    - /robot2/pose
  pose:
    - 5.0
    - 2.5
    - 0.0
robot3:
  topics:
    - /robot3/wp
    - /robot3/pose
  pose:
    - 0.0
    - 5.0
    - 0.0